In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.datasets import make_blobs
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from IPython.core.pylabtools import figsize
# use seaborn for plot defaults
# this can be safely commented out
import seaborn; seaborn.set()
from scipy import stats
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

# use seaborn plotting defaults
import seaborn as sns; sns.set()


In [2]:
import os
directory = "/Users/amad/Desktop/data/IMU"

for root, subdirectories, files in os.walk(directory):
    for subdirectory in subdirectories:
        print(os.path.join(root, subdirectory))
    for file in files:
        print(os.path.join(root, file))

/Users/amad/Desktop/data/IMU/TEJASAI_CHUNDRU - 2022-02-24 21.37.53 - TEJASAICHUNDRU3
/Users/amad/Desktop/data/IMU/Sai Venkatesh Atukuri - 2022-02-25 21.01.56 - SaiVenkatesh_IMU
/Users/amad/Desktop/data/IMU/Zoie Harris - Zoie_Harris
/Users/amad/Desktop/data/IMU/Wyatt Hackley - Wyatt_Hackley
/Users/amad/Desktop/data/IMU/Eric Yan - Eric_Yan_New
/Users/amad/Desktop/data/IMU/Michael Mungaray - Michael_Mungaray
/Users/amad/Desktop/data/IMU/Syed Amad H Shah - Syed_Shah
/Users/amad/Desktop/data/IMU/Nathan Tolodziecki - 2022-02-24 21.29.22 - Nathan_Tolodziecki
/Users/amad/Desktop/data/IMU/Aka'sh Carver - Akasha_Carver
/Users/amad/Desktop/data/IMU/Teegan Krieger - 2022-02-24 21.37.48 - Teegan_Krieger
/Users/amad/Desktop/data/IMU/Steven Tagner - 2022-02-24 21.16.09 - steven_tagner
/Users/amad/Desktop/data/IMU/Anthony Mesa - Anthony Mesa
/Users/amad/Desktop/data/IMU/McKenzie Staton - McKenzie_Staton
/Users/amad/Desktop/data/IMU/atreya - atreya_avadhanula
/Users/amad/Desktop/data/IMU/Anvesh - Anves

In [3]:
import os
from glob import glob
PATH = "/Users/amad/Desktop/data/IMU"
EXT = "*wave_data.csv"
wave = [file for path, subdir, files in os.walk(PATH)
                 for file in glob(os.path.join(path, EXT))]



In [4]:
 import os
from glob import glob
PATH = "/Users/amad/Desktop/data/IMU"
EXT = "*fistbump_data.csv"
fistbump = [file
                 for path, subdir, files in os.walk(PATH)
                 for file in glob(os.path.join(path, EXT))]


In [5]:
wave_files = ['/Users/amad/Desktop/data/IMU/TEJASAI_CHUNDRU - 2022-02-24 21.37.53 - TEJASAICHUNDRU3/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Sai Venkatesh Atukuri - 2022-02-25 21.01.56 - SaiVenkatesh_IMU/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Zoie Harris - Zoie_Harris/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Wyatt Hackley - Wyatt_Hackley/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Eric Yan - Eric_Yan_New/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Michael Mungaray - Michael_Mungaray/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Syed Amad H Shah - Syed_Shah/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Nathan Tolodziecki - 2022-02-24 21.29.22 - Nathan_Tolodziecki/wave_data.csv',
 "/Users/amad/Desktop/data/IMU/Aka'sh Carver - Akasha_Carver/wave_data.csv",
 '/Users/amad/Desktop/data/IMU/Teegan Krieger - 2022-02-24 21.37.48 - Teegan_Krieger/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Steven Tagner - 2022-02-24 21.16.09 - steven_tagner/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Anthony Mesa - Anthony Mesa/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/McKenzie Staton - McKenzie_Staton/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/atreya - atreya_avadhanula/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Anvesh - Anvesh_Avirneni New/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Carlos Ruiz - Carlos_Ruiz/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Pratik Devkota - Pratik_Devkota/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Tom Truong - Thomas_Truong_Fixed_IMU/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Connor Contursi - 2022-02-24 21.02.57 - Connor_Contursi/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Sardar Karan Singh - KaranSingh_Sardar/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Praneeth Aluru - Praneeth_Aluru_Task_1/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Thomas Knepshield - 2022-02-24 20.54.58 - Thomas_Knepshield/wave_data.csv']

In [6]:
wave


['/Users/amad/Desktop/data/IMU/TEJASAI_CHUNDRU - 2022-02-24 21.37.53 - TEJASAICHUNDRU3/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Sai Venkatesh Atukuri - 2022-02-25 21.01.56 - SaiVenkatesh_IMU/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Zoie Harris - Zoie_Harris/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Wyatt Hackley - Wyatt_Hackley/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Eric Yan - Eric_Yan_New/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Michael Mungaray - Michael_Mungaray/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Syed Amad H Shah - Syed_Shah/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Nathan Tolodziecki - 2022-02-24 21.29.22 - Nathan_Tolodziecki/wave_data.csv',
 "/Users/amad/Desktop/data/IMU/Aka'sh Carver - Akasha_Carver/wave_data.csv",
 '/Users/amad/Desktop/data/IMU/Teegan Krieger - 2022-02-24 21.37.48 - Teegan_Krieger/wave_data.csv',
 '/Users/amad/Desktop/data/IMU/Steven Tagner - 2022-02-24 21.16.09 - steven_tagner/wave_data.csv',
 '/Users/amad/Desktop

In [7]:
fistbump

['/Users/amad/Desktop/data/IMU/TEJASAI_CHUNDRU - 2022-02-24 21.37.53 - TEJASAICHUNDRU3/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Sai Venkatesh Atukuri - 2022-02-25 21.01.56 - SaiVenkatesh_IMU/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Zoie Harris - Zoie_Harris/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Wyatt Hackley - Wyatt_Hackley/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Eric Yan - Eric_Yan_New/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Michael Mungaray - Michael_Mungaray/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Syed Amad H Shah - Syed_Shah/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Nathan Tolodziecki - 2022-02-24 21.29.22 - Nathan_Tolodziecki/fistbump_data.csv',
 "/Users/amad/Desktop/data/IMU/Aka'sh Carver - Akasha_Carver/fistbump_data.csv",
 '/Users/amad/Desktop/data/IMU/Teegan Krieger - 2022-02-24 21.37.48 - Teegan_Krieger/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Steven Tagner - 2022-02-24 21.16.09 - steven_tagn

In [8]:
fistbump_files = ['/Users/amad/Desktop/data/IMU/TEJASAI_CHUNDRU - 2022-02-24 21.37.53 - TEJASAICHUNDRU3/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Sai Venkatesh Atukuri - 2022-02-25 21.01.56 - SaiVenkatesh_IMU/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Zoie Harris - Zoie_Harris/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Wyatt Hackley - Wyatt_Hackley/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Eric Yan - Eric_Yan_New/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Michael Mungaray - Michael_Mungaray/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Syed Amad H Shah - Syed_Shah/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Nathan Tolodziecki - 2022-02-24 21.29.22 - Nathan_Tolodziecki/fistbump_data.csv',
 "/Users/amad/Desktop/data/IMU/Aka'sh Carver - Akasha_Carver/fistbump_data.csv",
 '/Users/amad/Desktop/data/IMU/Teegan Krieger - 2022-02-24 21.37.48 - Teegan_Krieger/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Steven Tagner - 2022-02-24 21.16.09 - steven_tagner/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Anthony Mesa - Anthony Mesa/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/McKenzie Staton - McKenzie_Staton/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/atreya - atreya_avadhanula/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Anvesh - Anvesh_Avirneni New/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Carlos Ruiz - Carlos_Ruiz/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Pratik Devkota - Pratik_Devkota/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Tom Truong - Thomas_Truong_Fixed_IMU/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Connor Contursi - 2022-02-24 21.02.57 - Connor_Contursi/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Sardar Karan Singh - KaranSingh_Sardar/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Praneeth Aluru - Praneeth_Aluru_Task_1/fistbump_data.csv',
 '/Users/amad/Desktop/data/IMU/Thomas Knepshield - 2022-02-24 20.54.58 - Thomas_Knepshield/fistbump_data.csv']


In [9]:
waveData = pd.concat((pd.read_csv(i) for i in wave_files)) # Import
waveData.to_csv('/Users/amad/Desktop/wave_combined.csv', index = False)

In [10]:
fistbumpData = pd.concat((pd.read_csv(i) for i in fistbump_files))
fistbumpData.to_csv('/Users/amad/Desktop/fistbump_combined.csv', index= False)

In [11]:

df1 = pd.read_csv("/Users/amad/Desktop/495/wave_combined.csv")

df2 = pd.read_csv("/Users/amad/Desktop/495/fistbump_combined.csv")

In [12]:
df2

ax          aY         aZ       gX       gY       gZ  sample
0             1.254      -0.675     -1.297  121.765 -273.071   94.116       1
1             1.306      -0.793     -1.636   87.769 -267.639   90.698       1
2             1.432      -0.921     -1.995   30.823 -249.756   83.130       1
3             1.552      -1.052     -2.063  -42.664 -225.891   71.533       1
4             1.525      -1.110     -1.930  -95.642 -191.589   53.040       1
...             ...         ...        ...      ...      ...      ...     ...
126900        0.472      -0.108      0.818   -0.610    0.427   -5.066      50
126901        0.466      -0.114      0.801    0.122   -1.038   -4.639      50
126902        0.472      -0.130      0.803    3.357   -0.793   -5.310      50
126903        0.481      -0.123      0.810    4.333    0.366   -5.493      50
126904        0.474      -0.116      0.806    4.944    1.587   -4.578      50

[126905 rows x 7 columns]

In [13]:
df1

aX        aY         aZ        gX        gY          gZ  sample
0           0.071     0.288      0.912     7.385    23.804       1.709     1.0
1            0.13     0.047       0.53    46.448    30.884      -10.62     1.0
2           0.119    -0.153      0.802    19.165    -6.348     -14.404     1.0
3           0.008    -0.147      1.215   -19.958    -15.32      -9.399     1.0
4          -0.076    -0.084      1.144    -7.507   -10.803      -0.732     1.0
...           ...       ...        ...       ...       ...         ...     ...
126926      0.622    -0.736     -0.138    -0.244   -11.902       8.789    50.0
126927      0.627    -0.736      -0.15     1.404   -10.803       7.568    50.0
126928      0.632    -0.731     -0.157     1.038   -10.498       6.042    50.0
126929      0.637    -0.731     -0.163     0.977   -10.254       4.761    50.0
126930       0.64    -0.738     -0.172      2.38   -10.193       3.479    50.0

[126931 rows x 7 columns]

In [14]:
df1["label"] = "0"
df1.to_csv("wave_data.csv", index = False)
df2["label"] = "1"
df2.to_csv("fistbump_data.csv", index = False)

In [15]:
df1

aX        aY         aZ        gX        gY          gZ  \
0           0.071     0.288      0.912     7.385    23.804       1.709   
1            0.13     0.047       0.53    46.448    30.884      -10.62   
2           0.119    -0.153      0.802    19.165    -6.348     -14.404   
3           0.008    -0.147      1.215   -19.958    -15.32      -9.399   
4          -0.076    -0.084      1.144    -7.507   -10.803      -0.732   
...           ...       ...        ...       ...       ...         ...   
126926      0.622    -0.736     -0.138    -0.244   -11.902       8.789   
126927      0.627    -0.736      -0.15     1.404   -10.803       7.568   
126928      0.632    -0.731     -0.157     1.038   -10.498       6.042   
126929      0.637    -0.731     -0.163     0.977   -10.254       4.761   
126930       0.64    -0.738     -0.172      2.38   -10.193       3.479   

        sample label  
0          1.0     0  
1          1.0     0  
2          1.0     0  
3          1.0     0  
4          1.0     0  
...        ...   ...  
126926    50.0     0  
126927    50.0     0  
126928    50.0     0  
126929    50.0     0  
126930    50.0     0  

[126931 rows x 8 columns]

In [16]:
df2

ax          aY         aZ       gX       gY       gZ  sample  \
0             1.254      -0.675     -1.297  121.765 -273.071   94.116       1   
1             1.306      -0.793     -1.636   87.769 -267.639   90.698       1   
2             1.432      -0.921     -1.995   30.823 -249.756   83.130       1   
3             1.552      -1.052     -2.063  -42.664 -225.891   71.533       1   
4             1.525      -1.110     -1.930  -95.642 -191.589   53.040       1   
...             ...         ...        ...      ...      ...      ...     ...   
126900        0.472      -0.108      0.818   -0.610    0.427   -5.066      50   
126901        0.466      -0.114      0.801    0.122   -1.038   -4.639      50   
126902        0.472      -0.130      0.803    3.357   -0.793   -5.310      50   
126903        0.481      -0.123      0.810    4.333    0.366   -5.493      50   
126904        0.474      -0.116      0.806    4.944    1.587   -4.578      50   

       label  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
126900     1  
126901     1  
126902     1  
126903     1  
126904     1  

[126905 rows x 8 columns]

In [17]:
frames = [df1, df2]
mged = pd.concat(frames)

indx = np.arange(len(mged))
rndmged = np.random.permutation(indx)


rndmged=mged.sample(frac=1).reset_index(drop=True)

rndmged.to_csv("/Users/amad/Desktop/combined_gesture.csv", index = False)

In [18]:
gesture = pd.read_csv("/Users/amad/Desktop/495/combined_gesture.csv")

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [19]:
gesture = gesture.apply(pd.to_numeric, errors='coerce')
gesture=gesture.fillna(0)

In [20]:
gesture

aX     aY     aZ       gX      gY       gZ  sample  label
0       0.444  0.776  0.452    4.028   2.930   -0.854    13.0      1
1       0.896 -0.448  0.136   -1.770   1.282   -1.587     2.0      1
2       0.030 -0.173  1.002  -14.099  -1.099  -12.146    35.0      1
3       0.315  1.432  0.237  135.071  10.681  200.439     8.0      0
4       0.017  0.841  0.501    1.282  -1.831   -3.479    13.0      0
...       ...    ...    ...      ...     ...      ...     ...    ...
253833 -0.466 -0.304  0.589  205.322 -91.187  333.496    42.0      0
253834  0.956  0.677  0.089   44.922   7.568   14.343    41.0      0
253835 -0.277  0.291  0.860    8.179  26.062   65.674     4.0      1
253836  0.398  1.066 -0.043    4.028  13.855  -12.695    20.0      0
253837  0.949  0.262  0.034  -49.805 -22.095   23.804    12.0      1

[253838 rows x 8 columns]

In [21]:
X=gesture.drop(columns=['sample', 'label'])

In [22]:
y=gesture[['label']]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(203070, 6)
(203070, 1)
(50768, 6)
(50768, 1)


In [24]:
X_train

aX     aY     aZ       gX       gY       gZ
44497   0.217  1.316 -0.215   66.223   -0.732   17.212
102979  0.772 -0.185  0.224    2.686  -71.228   42.664
122691 -0.038  0.873 -0.417  -17.090    2.991   -1.038
228366  0.124  1.593 -0.368 -157.837  -39.246 -177.368
197468  0.836 -0.267  1.255  -61.890 -126.038  -35.583
...       ...    ...    ...      ...      ...      ...
232422  0.977 -0.151  0.013  -32.776   -3.906   12.451
124605 -0.666  1.502 -0.733 -112.122  239.258  233.093
20463   0.981  0.979 -0.211   32.104    1.831    0.916
18638   0.972 -0.198 -0.007    5.005    5.615   -0.122
35683   0.611  0.378 -0.621  -90.759  -34.851  -31.250

[203070 rows x 6 columns]

In [25]:
y_train

label
44497       0
102979      1
122691      1
228366      0
197468      1
...       ...
232422      1
124605      0
20463       0
18638       1
35683       1

[203070 rows x 1 columns]

# Logistic Regression

In [26]:
clf = LogisticRegression()
clf.fit(X_train, y_train)
predicted = clf.predict(X_test)
print(metrics.accuracy_score(y_test, predicted))

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.6026630948629058


In [27]:
predicted

array([0, 0, 0, ..., 1, 1, 0])

In [28]:
clf.predict_proba(X_test)

array([[0.55021359, 0.44978641],
       [0.66291327, 0.33708673],
       [0.53127626, 0.46872374],
       ...,
       [0.49273876, 0.50726124],
       [0.24569855, 0.75430145],
       [0.61603918, 0.38396082]])

In [29]:
clf.score(X_test, y_test)

0.6026630948629058

In [30]:
print("Classification report for classifier {clf}:")
print(metrics.classification_report(y_test, predicted))

Classification report for classifier {clf}:
              precision    recall  f1-score   support

           0       0.62      0.54      0.58     25481
           1       0.59      0.67      0.63     25287

    accuracy                           0.60     50768
   macro avg       0.60      0.60      0.60     50768
weighted avg       0.60      0.60      0.60     50768



In [31]:
cnf_matrix = confusion_matrix(y_test, predicted)
print(confusion_matrix(y_test, predicted))

[[13718 11763]
 [ 8409 16878]]


# Decision Tree

In [42]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [43]:
clf.predict_proba(X_test)
clf.score(X_test, y_test)

0.8711393003466751

In [44]:
predicted = clf.predict(X_test)
predicted

array([0, 1, 0, ..., 0, 0, 0])

In [45]:
print("Classification report for classifier {clf}:")
print(metrics.classification_report(y_test, predicted))


Classification report for classifier {clf}:
              precision    recall  f1-score   support

           0       0.86      0.88      0.87     25481
           1       0.88      0.86      0.87     25287

    accuracy                           0.87     50768
   macro avg       0.87      0.87      0.87     50768
weighted avg       0.87      0.87      0.87     50768



In [46]:
#plt.figure(figsize = (5,5))
#tree.plot_tree(clf, filled = True)

In [48]:
#plt.figure()
#visualize_tree(clf, X[:200], y[:200], boundaries=False)
#plt.figure()
#visualize_tree(clf, X[-200:], y[-200:], boundaries=False)

In [37]:
cnf_matrix = confusion_matrix(y_test, predicted)
print(confusion_matrix(y_test, predicted))

[[22466  3015]
 [ 3522 21765]]


# Random Forest

In [38]:
clf = RandomForestClassifier(n_estimators=50, random_state=50)
clf.fit(X_train, y_train)

<ipython-input-38-f3239ba3f4d1>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train, y_train)


In [49]:
clf.predict_proba(X_test)
predicted = clf.predict(X_test)
clf.score(X_test, y_test)

0.8711393003466751

In [40]:
print("Classification report for classifier {clf}:")
print(metrics.classification_report(y_test, predicted))

Classification report for classifier {clf}:
              precision    recall  f1-score   support

           0       0.89      0.89      0.89     25481
           1       0.89      0.89      0.89     25287

    accuracy                           0.89     50768
   macro avg       0.89      0.89      0.89     50768
weighted avg       0.89      0.89      0.89     50768



In [41]:
cnf_matrix = confusion_matrix(y_test, predicted)
print(confusion_matrix(y_test, predicted))

[[22802  2679]
 [ 2714 22573]]
